// Code generated by go-swagger; DO NOT EDIT.

package update_user_by_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutUserUserIDHandlerFunc turns a function with the right signature into a put user user ID handler
type PutUserUserIDHandlerFunc func(PutUserUserIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUserUserIDHandlerFunc) Handle(params PutUserUserIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutUserUserIDHandler interface for that can handle valid put user user ID params
type PutUserUserIDHandler interface {
	Handle(PutUserUserIDParams, interface{}) middleware.Responder
}

// NewPutUserUserID creates a new http.Handler for the put user user ID operation
func NewPutUserUserID(ctx *middleware.Context, handler PutUserUserIDHandler) *PutUserUserID {
	return &PutUserUserID{Context: ctx, Handler: handler}
}

/*
	PutUserUserID swagger:route PUT /user/{userId} update_user_by_id putUserUserId

update User by id
*/
type PutUserUserID struct {
	Context *middleware.Context
	Handler PutUserUserIDHandler
}

func (o *PutUserUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutUserUserIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
