version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'mydb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'myuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mydb.txt:/var/lib/mysql
      - initdb.sql:/docker-entrypoint-initdb.d/:ro
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
