// Code generated by go-swagger; DO NOT EDIT.

// Package restapi core
//
//	key/user management and authorization server
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/github.com.obarbier.custom-app.core.v1+json
//
//	Produces:
//	  - application/github.com.obarbier.custom-app.core.v1+json
//
// swagger:meta
package restapi
