// Code generated by go-swagger; DO NOT EDIT.

package update_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/obarbier/custom-app/core/pkg/models"
)

// PutUserOKCode is the HTTP code returned for type PutUserOK
const PutUserOKCode int = 200

/*
PutUserOK OK

swagger:response putUserOK
*/
type PutUserOK struct {
}

// NewPutUserOK creates PutUserOK with default headers values
func NewPutUserOK() *PutUserOK {

	return &PutUserOK{}
}

// WriteResponse to the client
func (o *PutUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutUserBadRequestCode is the HTTP code returned for type PutUserBadRequest
const PutUserBadRequestCode int = 400

/*
PutUserBadRequest bad request body

swagger:response putUserBadRequest
*/
type PutUserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.UserResponse `json:"body,omitempty"`
}

// NewPutUserBadRequest creates PutUserBadRequest with default headers values
func NewPutUserBadRequest() *PutUserBadRequest {

	return &PutUserBadRequest{}
}

// WithPayload adds the payload to the put user bad request response
func (o *PutUserBadRequest) WithPayload(payload *models.UserResponse) *PutUserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user bad request response
func (o *PutUserBadRequest) SetPayload(payload *models.UserResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserUnauthorizedCode is the HTTP code returned for type PutUserUnauthorized
const PutUserUnauthorizedCode int = 401

/*
PutUserUnauthorized unauthorized

swagger:response putUserUnauthorized
*/
type PutUserUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutUserUnauthorized creates PutUserUnauthorized with default headers values
func NewPutUserUnauthorized() *PutUserUnauthorized {

	return &PutUserUnauthorized{}
}

// WithPayload adds the payload to the put user unauthorized response
func (o *PutUserUnauthorized) WithPayload(payload *models.Error) *PutUserUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user unauthorized response
func (o *PutUserUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserNotFoundCode is the HTTP code returned for type PutUserNotFound
const PutUserNotFoundCode int = 404

/*
PutUserNotFound A user with the specified ID was not found.

swagger:response putUserNotFound
*/
type PutUserNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutUserNotFound creates PutUserNotFound with default headers values
func NewPutUserNotFound() *PutUserNotFound {

	return &PutUserNotFound{}
}

// WithPayload adds the payload to the put user not found response
func (o *PutUserNotFound) WithPayload(payload *models.Error) *PutUserNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user not found response
func (o *PutUserNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PutUserDefault error

swagger:response putUserDefault
*/
type PutUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutUserDefault creates PutUserDefault with default headers values
func NewPutUserDefault(code int) *PutUserDefault {
	if code <= 0 {
		code = 500
	}

	return &PutUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put user default response
func (o *PutUserDefault) WithStatusCode(code int) *PutUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put user default response
func (o *PutUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put user default response
func (o *PutUserDefault) WithPayload(payload *models.Error) *PutUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user default response
func (o *PutUserDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
