// Code generated by go-swagger; DO NOT EDIT.

package get_all

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUserAllHandlerFunc turns a function with the right signature into a get user all handler
type GetUserAllHandlerFunc func(GetUserAllParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserAllHandlerFunc) Handle(params GetUserAllParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserAllHandler interface for that can handle valid get user all params
type GetUserAllHandler interface {
	Handle(GetUserAllParams, interface{}) middleware.Responder
}

// NewGetUserAll creates a new http.Handler for the get user all operation
func NewGetUserAll(ctx *middleware.Context, handler GetUserAllHandler) *GetUserAll {
	return &GetUserAll{Context: ctx, Handler: handler}
}

/*
	GetUserAll swagger:route GET /user/all get_all getUserAll

Returns a list of users.

allow to query all users in the system
*/
type GetUserAll struct {
	Context *middleware.Context
	Handler GetUserAllHandler
}

func (o *GetUserAll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUserAllParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
