// Code generated by go-swagger; DO NOT EDIT.

package get_all

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/obarbier/custom-app/core/pkg/models"
)

// GetUserAllOKCode is the HTTP code returned for type GetUserAllOK
const GetUserAllOKCode int = 200

/*
GetUserAllOK OK

swagger:response getUserAllOK
*/
type GetUserAllOK struct {

	/*
	  In: Body
	*/
	Payload models.ArrayOfUser `json:"body,omitempty"`
}

// NewGetUserAllOK creates GetUserAllOK with default headers values
func NewGetUserAllOK() *GetUserAllOK {

	return &GetUserAllOK{}
}

// WithPayload adds the payload to the get user all o k response
func (o *GetUserAllOK) WithPayload(payload models.ArrayOfUser) *GetUserAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user all o k response
func (o *GetUserAllOK) SetPayload(payload models.ArrayOfUser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ArrayOfUser{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUserAllUnauthorizedCode is the HTTP code returned for type GetUserAllUnauthorized
const GetUserAllUnauthorizedCode int = 401

/*
GetUserAllUnauthorized unauthorized

swagger:response getUserAllUnauthorized
*/
type GetUserAllUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserAllUnauthorized creates GetUserAllUnauthorized with default headers values
func NewGetUserAllUnauthorized() *GetUserAllUnauthorized {

	return &GetUserAllUnauthorized{}
}

// WithPayload adds the payload to the get user all unauthorized response
func (o *GetUserAllUnauthorized) WithPayload(payload *models.Error) *GetUserAllUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user all unauthorized response
func (o *GetUserAllUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserAllUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetUserAllDefault error

swagger:response getUserAllDefault
*/
type GetUserAllDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserAllDefault creates GetUserAllDefault with default headers values
func NewGetUserAllDefault(code int) *GetUserAllDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserAllDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user all default response
func (o *GetUserAllDefault) WithStatusCode(code int) *GetUserAllDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user all default response
func (o *GetUserAllDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user all default response
func (o *GetUserAllDefault) WithPayload(payload *models.Error) *GetUserAllDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user all default response
func (o *GetUserAllDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserAllDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
